function transformDataStructure(arr) {
  const res = {};
  treeTraverse(arr, res);
  return res;
}

function treeTraverse(tree, collect = {}) {
  tree.forEach((item) => {
    if (item.type == "Object") {
      Object.assign(collect, { [`${item.mappingValue}`]: {} });
      if (item.childParam && item.childParam.length > 0) {
        treeTraverse(item.childParam, collect[`${item.mappingValue}`]);
      }
    } else if (item.type == "Object[]") {
      Object.assign(collect, { [`${item.mappingValue}`]: [{}] });
      if (item.childParam && item.childParam.length > 0) {
        treeTraverse(item.childParam, collect[`${item.mappingValue}`][0]);
      }
    } else {
      let val = "";
      if (["boolean", "Boolean"].includes(item.type)) {
        val = false;
      }
      if (["int", "integer"].includes(item.type)) {
        val = 1;
      }
      if (item.type == "double") {
        val = 6.6666;
      }
      Object.assign(collect, { [`${item.mappingValue}`]: val });
    }
  });
}

console.log(
  JSON.stringify(
    transformDataStructure([
      {
        defaultValue: null,
        length: null,
        sort: null,
        type: "Object",
        example: "",
        mappingValue: "result",
        opt: null,
        name: "result",
        isMapping: true,
        childParam: [
          {
            defaultValue: null,
            length: null,
            sort: null,
            type: "Object[]",
            example: "",
            mappingValue: "printSuccessList",
            opt: null,
            name: "result.printSuccessList",
            isMapping: true,
            childParam: null,
            needDisplayPC: true,
            remarks: "打印成功列表",
          },
          {
            defaultValue: null,
            length: null,
            sort: null,
            type: "Object[]",
            example: "",
            mappingValue: "printErrorList",
            opt: null,
            name: "result.printErrorList",
            isMapping: true,
            childParam: null,
            needDisplayPC: true,
            remarks: "打印失败列表",
          },
        ],
        needDisplayPC: true,
        remarks: "打印结果",
      },
      {
        defaultValue: null,
        length: null,
        sort: null,
        type: "Boolean",
        example: "true",
        mappingValue: "status",
        opt: null,
        name: "status",
        isMapping: true,
        childParam: null,
        needDisplayPC: true,
        remarks: "是否成功 true 成功 false 失败",
      },
      {
        defaultValue: null,
        length: null,
        sort: null,
        type: "string",
        example: "内部错误",
        mappingValue: "message",
        opt: null,
        name: "message",
        isMapping: true,
        childParam: null,
        needDisplayPC: true,
        remarks: "内部消息",
      },
      {
        defaultValue: null,
        length: null,
        sort: null,
        type: "string",
        example: "C100",
        mappingValue: "statusCode",
        opt: null,
        name: "statusCode",
        isMapping: true,
        childParam: null,
        needDisplayPC: true,
        remarks: "状态码",
      },
    ]),
    null,
    2
  )
);

// https://newsn.net/say/nodejs-print-object.html

// console.dir(
//   transformDataStructure([
//     {
//       defaultValue: null,
//       length: null,
//       sort: "0",
//       type: "string",
//       example: "",
//       mappingValue: "printerId",
//       opt: false,
//       name: "printerId",
//       isMapping: true,
//       childParam: null,
//       needDisplayPC: true,
//       remarks:
//         "打印机名称（PC端普通打印机必传），获取方式：电脑控制面板-设备与打印机界面选中打印机右键选择打印机属性，打印机名称内会展示",
//     },
//     {
//       defaultValue: null,
//       length: null,
//       sort: "0",
//       type: "string",
//       example: "8C:EC:4B:1B:D0:52",
//       mappingValue: "deviceId",
//       opt: false,
//       name: "deviceId",
//       isMapping: true,
//       childParam: null,
//       needDisplayPC: true,
//       remarks: "设备id（设备id或二维码id二者必传其一）",
//     },
//     {
//       defaultValue: null,
//       length: null,
//       sort: "0",
//       type: "string",
//       example: "xpe33k5v",
//       mappingValue: "qrcodeId",
//       opt: false,
//       name: "qrcodeId",
//       isMapping: true,
//       childParam: null,
//       needDisplayPC: true,
//       remarks: "二维码id（设备id或二维码id二者必传其一）",
//     },
//     {
//       defaultValue: null,
//       length: null,
//       sort: "0",
//       type: "string",
//       example: "ZOP",
//       mappingValue: "printChannel",
//       opt: true,
//       name: "printChannel",
//       isMapping: true,
//       childParam: null,
//       needDisplayPC: true,
//       remarks: "打印渠道(填写：ZOP)",
//     },
//     {
//       defaultValue: null,
//       length: null,
//       sort: "0",
//       type: "Object[]",
//       example: "",
//       mappingValue: "printInfos",
//       opt: true,
//       name: "printInfos",
//       isMapping: true,
//       childParam: [
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "200420036914037103",
//           mappingValue: "partnerCode",
//           opt: true,
//           name: "printInfos.partnerCode",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "订单号",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "Object",
//           example: "",
//           mappingValue: "printParam",
//           opt: true,
//           name: "printInfos.printParam",
//           isMapping: false,
//           childParam: [
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "ELEC_MARK",
//               mappingValue: "paramType",
//               opt: true,
//               name: "printInfos.printParam.paramType",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "ELEC_MARK：指定电子面单和指定大头笔信息 ELEC_NOMARK：指定电子面单和不指定大头笔信息 NOELEC_MARK：不指定电子面单和指定大头笔信息（需传电子面单账号密码获取运单号） NOELEC_NOMARK：不指定电子面单和不指定大头笔信息（需传电子面单账号密码获取运单号） DEFAULT_PRINT：采用默认电子面单账号",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "73111338944567",
//               mappingValue: "mailNo",
//               opt: false,
//               name: "printInfos.printParam.mailNo",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "运单号(paramType：ELEC_MARK必传；ELEC_NOMARK必传；即指定电子面单必传）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "",
//               mappingValue: "elecAccount",
//               opt: false,
//               name: "printInfos.printParam.elecAccount",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "电子面单账号（paramType：NOELEC_MARK必传；NOELEC_NOMARK必传；即不指定电子面单必传）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "",
//               mappingValue: "elecPwd",
//               opt: false,
//               name: "printInfos.printParam.elecPwd",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "电子面单密码（paramType：NOELEC_MARK必传；NOELEC_NOMARK必传；即不指定电子面单必传）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "300- C-09 011",
//               mappingValue: "printMark",
//               opt: false,
//               name: "printInfos.printParam.printMark",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "大头笔(paramType：ELEC_MARK必传；NOELEC_MARK必传；即指定大头笔必传）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "沪西",
//               mappingValue: "printBagaddr",
//               opt: false,
//               name: "printInfos.printParam.printBagaddr",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "集包地 (paramType：ELEC_MARK必传；NOELEC_MARK必传；即指定大头笔必传）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "015",
//               mappingValue: "paiMan",
//               opt: false,
//               name: "printInfos.printParam.paiMan",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "派件业务员编号",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "县医院",
//               mappingValue: "fourCode",
//               opt: false,
//               name: "printInfos.printParam.fourCode",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "四段码",
//             },
//           ],
//           needDisplayPC: true,
//           remarks: "打印参数",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "Object",
//           example: "",
//           mappingValue: "sender",
//           opt: true,
//           name: "printInfos.sender",
//           isMapping: false,
//           childParam: [
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "李冰",
//               mappingValue: "name",
//               opt: true,
//               name: "printInfos.sender.name",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "寄件姓名",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "15026692250",
//               mappingValue: "mobile",
//               opt: true,
//               name: "printInfos.sender.mobile",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "寄件手机号，手机号和电话二选一",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "陕西省",
//               mappingValue: "prov",
//               opt: true,
//               name: "printInfos.sender.prov",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "寄件省",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "西安市",
//               mappingValue: "city",
//               opt: true,
//               name: "printInfos.sender.city",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "寄件市",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "未央区",
//               mappingValue: "county",
//               opt: true,
//               name: "printInfos.sender.county",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "寄件区",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "雨润农产品物流",
//               mappingValue: "address",
//               opt: true,
//               name: "printInfos.sender.address",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "寄件详细地址",
//             },
//           ],
//           needDisplayPC: true,
//           remarks: "寄件人信息",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "Object",
//           example: "",
//           mappingValue: "receiver",
//           opt: true,
//           name: "printInfos.receiver",
//           isMapping: false,
//           childParam: [
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "巴拉巴拉",
//               mappingValue: "name",
//               opt: true,
//               name: "printInfos.receiver.name",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "收件姓名",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "15026692256",
//               mappingValue: "mobile",
//               opt: true,
//               name: "printInfos.receiver.mobile",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "收件手机，手机和电话二者必传其一",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "陕西省",
//               mappingValue: "prov",
//               opt: true,
//               name: "printInfos.receiver.prov",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "收件省",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "西安市",
//               mappingValue: "city",
//               opt: true,
//               name: "printInfos.receiver.city",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "收件市",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "雁塔区",
//               mappingValue: "county",
//               opt: true,
//               name: "printInfos.receiver.county",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "收件区",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "北池头二路中海东郡20号楼",
//               mappingValue: "address",
//               opt: true,
//               name: "printInfos.receiver.address",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "收件详细地址",
//             },
//           ],
//           needDisplayPC: true,
//           remarks: "收件人信息",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "boolean",
//           example: "false",
//           mappingValue: "repetition",
//           opt: false,
//           name: "printInfos.repetition",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "重复打单模式(true 重复打单)",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "Object",
//           example: "",
//           mappingValue: "goods",
//           opt: false,
//           name: "printInfos.goods",
//           isMapping: false,
//           childParam: [
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "",
//               mappingValue: "goodsName",
//               opt: false,
//               name: "printInfos.goods.goodsName",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "物品名称",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "long",
//               example: "1000",
//               mappingValue: "weight",
//               opt: false,
//               name: "printInfos.goods.weight",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "物品重量（单位：克）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "long",
//               example: "",
//               mappingValue: "freight",
//               opt: false,
//               name: "printInfos.goods.freight",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "运费金额（单位：分）",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "",
//               mappingValue: "remark",
//               opt: false,
//               name: "printInfos.goods.remark",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "订单备注",
//             },
//           ],
//           needDisplayPC: true,
//           remarks: "物品信息",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "boolean",
//           example: "true",
//           mappingValue: "checked",
//           opt: false,
//           name: "printInfos.checked",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "是否验视 默认：true",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "",
//           mappingValue: "staffCode",
//           opt: false,
//           name: "printInfos.staffCode",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "业务员编号",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "CASH",
//           mappingValue: "payType",
//           opt: false,
//           name: "printInfos.payType",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "付款方式（到付：COSTD；现付：CASH；月结：MS）",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "PRINT_SHEET",
//           mappingValue: "sheetMode",
//           opt: false,
//           name: "printInfos.sheetMode",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks:
//             "打印模板（一联单（76*130）； 普通联：PRINT_SHEET； 寄件联：PRINT_SENDPAGE； 普通联+寄件联：PRINT_SHEET_SENDPAGE； 二联单(100*180)：TWO_NORMAL_100_180 三联单(100*180)：THREE_NORMAL_100_180 三联单(76*203)：THREE_NORMAL_76_203）",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "Object[]",
//           example: "",
//           mappingValue: "appreciationDTOS",
//           opt: false,
//           name: "printInfos.appreciationDTOS",
//           isMapping: false,
//           childParam: [
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "integer",
//               example: "",
//               mappingValue: "type",
//               opt: false,
//               name: "printInfos.appreciationDTOS.type",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks:
//                 "增值服务类型（代收货款：2；到付：1；保价：18；尊享：6；标快：29）；隐私服务：16",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "integer",
//               example: "",
//               mappingValue: "amount",
//               opt: false,
//               name: "printInfos.appreciationDTOS.amount",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "增值服务金额(代收金额，保价金额，到付金额)",
//             },
//             {
//               defaultValue: null,
//               length: null,
//               sort: "0",
//               type: "string",
//               example: "",
//               mappingValue: "backBillCode",
//               opt: false,
//               name: "printInfos.appreciationDTOS.backBillCode",
//               isMapping: false,
//               childParam: null,
//               needDisplayPC: true,
//               remarks: "回单号(签单返还时填写)",
//             },
//           ],
//           needDisplayPC: true,
//           remarks: "增值服务消息列表",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "",
//           mappingValue: "takingEmpCode",
//           opt: false,
//           name: "printInfos.takingEmpCode",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "揽件业务员code",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "",
//           mappingValue: "tenantName",
//           opt: false,
//           name: "printInfos.tenantName",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "商户名称",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "string",
//           example: "",
//           mappingValue: "partnerId",
//           opt: false,
//           name: "printInfos.partnerId",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "订单类型(星联订单标记：包含 starunion )",
//         },
//         {
//           defaultValue: null,
//           length: null,
//           sort: "0",
//           type: "int",
//           example: "",
//           mappingValue: "realName",
//           opt: false,
//           name: "printInfos.realName",
//           isMapping: false,
//           childParam: null,
//           needDisplayPC: true,
//           remarks: "是否实名(默认：0；1：未实名；2：已实名)",
//         },
//       ],
//       needDisplayPC: true,
//       remarks: "打印数据",
//     },
//   ]),
//   { depth: null }
// );
